name: Deploy Azure Job API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set version tag
      run: |
        VERSION=v${{ github.run_number }}
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  

    - name: Docker Login to ACR
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
  
    - name: Build Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build --platform linux/amd64 \
          -t ${{ secrets.ACR_LOGIN_SERVER }}/job-aggregator-api:$IMAGE_TAG \
          -t ${{ secrets.ACR_LOGIN_SERVER }}/job-aggregator-api:${{ env.VERSION }} \
          ./app/azure/api

    - name: Push image to ACR
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/job-aggregator-api:$IMAGE_TAG
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/job-aggregator-api:${{ env.VERSION }

    # 🚀 Deploy to STAGING (change here)
    - name: Deploy to staging
      run: |
        IMAGE_TAG=${{ github.sha }}
        az containerapp update \
          --name job-api-staging \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --image ${{ secrets.ACR_LOGIN_SERVER }}/job-aggregator-api:$IMAGE_TAG

     # ⏳ Wait
    - name: Wait for app to start
      run: sleep 20

     # ❤️ Health check
    - name: Health check
      run: |
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://<staging-url>/health)
        if [ "$STATUS" -ne 200 ]; then
          echo "Health check failed"
          exit 1
        fi


